
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "salayaazmrghyqjddagm"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
schemes = ["http", "https"]

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[email]
enabled = true
# Port to use for the SMTP server.
port = 54324
# The default sender address for emails sent from the dev setup.
default_sender = "onboarding@resend.dev"

[auth]
enabled = true
# Updated site_url to match the new domain
site_url = "https://homimatch.com"
additional_redirect_urls = ["https://homimatch.com/verified", "https://homimatch.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = true
client_id = "TU_GOOGLE_CLIENT_ID_REAL"
secret = "TU_GOOGLE_CLIENT_SECRET_REAL"

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Setup BigQuery support
backend = "postgres"

# Configure one of the supported backends
[analytics.backends.postgres]
enabled = true

# Enable, but don't start the Postgres extensions/plugins
[extensions.postgres]
enabled = false

[extensions.postgres.extensions.vector]
enabled = true

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323

# If true, Browse, Database, and Reports don't connect directly to Postgres (port 5432) from the browser.
# Instead, the Studio server acts as a proxy.
# If false, the browser connects directly to Postgres.
# If you're running Supabase on your local machine, you can set this to false.
# If you're running Supabase on a remote machine, you should set this to true.
use_proxy = true

[functions]
[functions.send-verification-email]
verify_jwt = false

[realtime]
enabled = true
